version: "3.9"

x-common_env: &common_env
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
    app:
        build: .
        volumes:
            - .:/var/www/html
        environment:
            <<: *common_env
            MYSQL_DSN: mysql:host=${MYSQL_HOST};dbname=${MYSQL_DATABASE};charset=utf8mb4
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            <<: *common_env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/:/docker-entrypoint-initdb.d:ro
    nginx:
        image: nginx:1.27
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

volumes:
    db_data:
